// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmxniivvcwzwitwvklyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNteG5paXZ2Y3d6d2l0d3ZrbHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTkyNTMsImV4cCI6MjA2NTUzNTI1M30.pYTQfQL7BMo7gzhBz7mz2kwOHEGsgnEKrP14vyaH4Dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);